export const ADD_ITEM_TO_CART = "CART_ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_CART = "UPDATE_CART";
